### ISSUE TITLE
Add a stack machine library for Ebiten.

### ISSUE THREAD

**Issue by PenguinCabinet** [sedyh/awesome-ebiten#2]
Hello! Nice to meet you.
This awesome list is good!

# Summary
I am making [the state and stack machine library for the game programming using Ebiten](https://github.com/PenguinCabinet/pgfsm).
It provides the state and stack machine for the game programming.
If you don't mind, I'd like to add it to this awesome list.

**Comment by PenguinCabinet** [comment]
Thank you for replying and telling me.
I understood those.
When I finish those changes,I am going to mention to you and open a PR.

**Comment by PenguinCabinet** [comment]
Hi.

# Summary
* Change all names (repo/types/functions/etc) according to the naming convention and generally accepted standards in golang.
  * https://github.com/PenguinCabinet/pgfsm
  * I changed the repo to the name that is one word and use only lower case letters for standards in golang.
  * I changed names of types and functions to the ones of Camel Case for standards in golang.
* Arrange comments on types/functions, and make documentation on pkg.go.dev.
Add tags to get package by version number.
  * Please watch [here](https://pkg.go.dev/github.com/PenguinCabinet/pgfsm#section-documentation).
* Add tags to get package by version number.
   * I issued [the tag](https://github.com/PenguinCabinet/pgfsm/tree/v0.0.2)
* Make a tutorial and quick start in English and add a couple of examples using this library.
  * I made [the tutorial of English](https://github.com/PenguinCabinet/pgfsm/blob/master/doc/Tutorial_en.md).
  * I wrote [quick start](https://github.com/PenguinCabinet/pgfsm/blob/master/README_en.md#quick-start) in README_en.md.
* Add unit tests, if possible.
  * I made [the unit tests](https://github.com/PenguinCabinet/pgfsm/blob/master/gsm_test.go).
* Make a fork and issue an offer as a PR.
  * I opened [a PR](https://github.com/sedyh/awesome-ebiten/pull/3).

**Comment by sedyh** [comment]
Hi, sorry for the long wait.

- There are still snake case variables in QuickStart and /test/main.go.
- Could you add a small separate project that would use this lib to the examples/ folder?
- I'm wondering why use new() instead of separate constructors? Just so as not to initialize the internal structures ahead of time?

I think a linter can very quickly suggest what can be done (like golangci-lint).

**Comment by PenguinCabinet** [comment]
Hi,thank you for your reviewing.
* There are still snake case variables in QuickStart and /test/main.go.
  * I finished changing all snake case variables into the ones of Camel Case in README.md, README_en.md and Tutorial_en.md.
    * I'm going to fix Tutorial.md.
* Could you add a very small separate project that would use this lib to the /examples folder?
    * I made [examples](https://github.com/PenguinCabinet/pgfsm/tree/master/examples) based by Tutorial.
* I'm wondering why use new() instead of separate constructors? Just so as not to initialize the internal structures ahead of time?
   * Hmm...There is no particular meaning.Should I use separate constructors instead of new()?
* I set to run [golangci-lint](https://github.com/PenguinCabinet/pgfsm/blob/master/.github/workflows/lint.yml) on Github Action.

**Comment by sedyh** [comment]
Hello. Sorry to bother you, could you also fix the snake case in the readme and run it through gofmt as well?

Regarding individual constructors, in the examples, immediately after initialization, fields are set (screen sizes and the first scene).
I think it’s still worth taking them out separately, it’s better to let the package deal with initialization itself, it will be easier to maintain later.
https://web3.coach/golang-why-you-should-use-constructors

**Comment by PenguinCabinet** [comment]
Hi,No problem.Thank you for your teaching.

* I finished changing all snake case variables to the ones of camel case.snake case variables is extinct.
* I used separate constructors instead of new().
* I run it through gofmt but nothing changed.I think the Go extension applies  automatically gofmt to source codes I use it of VS code.

**Comment by sedyh** [comment]
Okay, the repository has been added to the list.

**Comment by PenguinCabinet** [comment]
Thank yooooooooooou for that you teach to me politely!!!!!
I could add it to the list by your help!!
