### ISSUE TITLE
Some GUI section entries are really out of date or do not provide sufficient doc

### ISSUE THREAD

**Issue by harbdog** [sedyh/awesome-ebiten#8]
I'm trying to find a good UI library and found that many currently listed have some issues, such as being really out of date or completely lacking in documentation.

From https://github.com/sedyh/awesome-ebiten#gui

Here are my notes on those that you may want to consider removal of and why (or at least archiving some that are not Ebiten v2.x supported):

[ebitenui](https://github.com/blizzy78/ebitenui) - A user interface engine and widget library for Ebiten.
- this one looks great, but there's a note that it has been archived by the owner as read-only?

[egui](https://github.com/xackery/egui) - Ebiten Graphical User Interface (and Framework).
- last updated January 2020
- not upgraded to use ebiten v2.x
- no usage documentation in README

[gameui](https://github.com/martinlindhe/gameui) - A game UI for golang with boilerplate to run with Ebiten.
- last updated April 2017
- not upgraded to use ebiten v2.x
- does not use go.mod

[gosprite](https://github.com/magicsea/gosprite) - Easy to use go drawing library, cocos-like interface, providing simple 2d drawing and simple UI.
- not upgraded to use ebiten v2.x
- no usage documentation in README
- shady looking link in README to IP address without `https`

[goui](https://github.com/kpfaulkner/goui) - UI library for creating desktop applications.
- last updated August 2020
- not upgraded to use ebiten v2.x

**Comment by sedyh** [comment]
Hello just noticed that ebitenui is zipped. Sadly, we don't have many libraries for ui right now.
About everyone else - I completely agree.

**Comment by harbdog** [comment]
ebiten-imgui is what I ended up settling on, works pretty good, maybe it should at least be bumped above ebitenui since it is archived.

**Comment by sedyh** [comment]
Yeah I also think so.

**Comment by quasilyte** [comment]
ebitenui is alive again btw.
So it's good that it's still on the list.
